on:
  push:
    branches: [main]
  pull_request:

name: check
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: fmt
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo +nightly fmt --check
        run: cargo +nightly fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: clippy
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all-targets