on:
  push:
    branches: [main]
  pull_request:

name: test
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test
        run: cargo test